---
monitors:
  google:
    - name: Google
      type: http
      url: https://google.com
    - name: Gmail
      type: http
      url: https://mail.google.com
  homelab:
    - name: PI Server
      type: ping
      hostname: 192.168.178.179
    - name: Windows Desktop
      type: ping
      hostname: 192.168.178.177
#  default:
#    - name: Personal Website
#      type: http
#      url: https://dalwar23.com
#  acme:
#    - name: acme
#      type: http
#      url: https://acme.operaitons1.app
