---
monitors:
  google:
    - name: Google
      type: http
      url: https://google.com
    - name: Gmail
      type: http
      url: https://mail.google.com
  homelab:
    - name: PI Server
      type: ping
      hostname: 192.168.178.179
    - name: Windows Desktop
      type: ping
      hostname: 192.168.178.177
  default:
    - name: Personal Website
      type: http
      url: https://dalwar23.com
    - name: MacBook Pro
      type: ping
      hostname: 192.168.178.188
  acme:
    - name: http-acme
      type: http
      url: https://acme.operations1.app

# TODO: Validation check for group name and process name can not be same
# TODO: Missing arguments should skip the process and show notification in run summary
